config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  telegram_webhooks TelegramWebhooksController
  devise_for :users, :path_prefix => 'my'

  resources :roles
  resources :users
  resources :notes do
    collection do
      get :all_notes
      get :get_user_notes
    end
  end
  resources :application do
    collection do
      post :index
    end
  end

  root to: 'notes#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/note.rb
# frozen_string_literal: true
class Note < ApplicationRecord
  belongs_to :user

  validates :title, presence: true, length: { in: 1..255 }
  validates :content, length: { maximum: 1023 }
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_note, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  layout 'notes', only: [:index]

  def index
    @notes = Note.where(user_id: current_user)
    @notes_by_date = @notes.group_by(&:date_appointment)
    @date = params[:date] ? DateTime.parse(params[:date]) : Time.now
  end

  def all_notes
    @notes = (current_user.admin? || current_user.head? ) ? Note.all : Note.where(user_id: current_user)
    @notes_by_date = @notes.group_by(&:date_appointment)
    @date = params[:date] ? DateTime.parse(params[:date]) : Time.now
  end

  def get_user_notes(user_id)
    @notes = (current_user.admin? || current_user.head? ) ? Note.all : Note.where(user_id: user_id)
    @notes_by_date = @notes.group_by(&:date_appointment)
    @date = params[:date] ? DateTime.parse(params[:date]) : Time.now
  end

  def show
  end

  def get_notes
    @telegram_notes = Note.all
  end

  def new(user_id = current_user.id)
    @note = Note.new
    @note.user_id = user_id
  end

  def edit
  end

  def create(*args)
    @note = Note.new(note_params)
    @note.date_appointment = @note.appointment.to_date
    @note.user_id = note_params.has_key?(:user_id) ? note_params.fetch(:user_id) : current_user.id
    respond_to do |format|
      if @note.save
        format.html { redirect_to @note, notice: 'Note was successfully created.' }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @note.update(note_params)
        # @note.date_appointment = @note.appointment.to_date
        @note.update_attributes!(date_appointment: @note.appointment.to_date)
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: 'Note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_note
    @note = Note.find(params[:id])
    redis = Redis.new
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def note_params
    params.require(:note).permit(:title, :content, :appointment, :date, :date_appointment, :user_id)
  end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_form.html.haml
=form_for(@note) do |f|
  -if @note.errors.any?
    %div{id: "error_explanation"}
      -@note.errors.full_messages.each do |message|
        =flash[:alert]=message

  %div.field
    %p
      =f.label :title, {class: "label label-default"}
    %div
      =f.text_field :title, {class: 'form-control input-sm'}

  %div.field
    %p
      =f.label :content, {class: "label label-default"}
    %div
      =f.text_area :content, {class: 'form-control input-sm'}

  %div.field
    %p
      =f.label :appointment, {class: "label label-default"}
    %div
      =f.datetime_select :appointment, {class: 'form-control input-sm', label: 'Appointment'}, default: 0.days.from_now.in_time_zone(Time.zone)
  -if current_user.admin? || current_user.head?
    %div.field
      %p
        =f.label :user_id, {class: "label label-default"}
      %div
        = f.collection_select :user_id, User.all, :id, :email, include_blank: true

  %div.actions
    =f.submit 'Submit', class: 'btn btn-success'
    =link_to 'Back', notes_path, {class: 'btn btn-default'}

app/views/notes/all_notes.html.haml
%h1 Notes

%div{id: "notes"}
  %h2{ style: 'text-align: center', id: 'month'}
    = link_to '<', date: @date.prev_month
    = @date.strftime('%B %Y')
    = link_to '>', date: @date.next_month

  = calendar(@date) do |date|
    = date.day
    - if (@notes_by_date[date])
      - @notes_by_date[date].each do |note|
        .container-fluid
          -if note.appointment < Time.now
            %li= note.appointment.strftime("%H:%M")
            = link_to note.title, note, {style:'color: red;', class: "css_class"}

          -if note.appointment >= Time.now
            %li= note.appointment.strftime("%H:%M")
            = link_to note.title, note, {style:'color: green;', class: "css_class"}


- if can? :create, Note
  = link_to 'New Note', new_note_path, class: 'btn btn-default'

app/views/notes/edit.html.haml
%h1
  Editing Note
%div.col-sm-8
  =render 'form', note: @note
  %div{class: 'btn-group btn-group'}
    =link_to 'Show', @note, {class: 'btn btn-default'}

app/views/notes/get_user_notes.html.haml
%h1 Notes

%div{id: "notes"}
  %h2{ style: 'text-align: center', id: 'month'}
    = link_to '<', date: @date.prev_month
    = @date.strftime('%B %Y')
    = link_to '>', date: @date.next_month

  = calendar(@date) do |date|
    = date.day
    - if (@notes_by_date[date])
      - @notes_by_date[date].each do |note|
        .container-fluid
          -if note.appointment < Time.now
            %li= note.appointment.strftime("%H:%M")
            = link_to note.title, note, {style:'color: red;', class: "css_class"}

          -if note.appointment >= Time.now
            %li= note.appointment.strftime("%H:%M")
            = link_to note.title, note, {style:'color: green;', class: "css_class"}


- if can? :create, Note
  = link_to 'New Note', new_note_path, class: 'btn btn-default'

app/views/notes/index.html.haml
%h1
  Notes

%div{id: "notes"}
  %h2{ style: 'text-align: center', id: 'month'}
    = link_to '<', date: @date.prev_month
    = @date.strftime('%B %Y')
    = link_to '>', date: @date.next_month

  = calendar(@date) do |date|
    = date.day
    - if (@notes_by_date[date])
      - @notes_by_date[date].each do |note|
        .container-fluid
          -if note.appointment < DateTime.now
            %li= note.appointment.strftime("%H:%M")
            = link_to note.title, note, {style:'color: red;', class: "css_class"}

          -if note.appointment >= Time.now
            %li= note.appointment.strftime("%H:%M")
            = link_to note.title, note, {style:'color: green;', class: "css_class"}


- if can? :create, Note
  = link_to 'New Note', new_note_path, class: 'btn btn-default'

app/views/notes/new.html.haml
%h1
  New Note

%div{class: "col-sm-8"}
  = render 'form', note: @note

app/views/notes/show.html.haml
%h1 Note info
.col-sm-8
  %table.table.table-default
    %tr
      %td Title:
      %td= @note.title
    %tr
      %td Content:
      %td= @note.content
    %tr
      %td Appointment:
      %td= @note.appointment
  .btn.btn-group
    - if can? :update, @note
      = link_to 'Edit', edit_note_path(@note), class: 'btn btn-default'
    = link_to 'Back', notes_path, class: 'btn btn-default'
    - if can? :destroy, @note
      = link_to 'Destroy', @note, method: :delete, class: 'btn btn-default', data: { confirm: 'Are you sure?' }