config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  telegram_webhooks TelegramWebhooksController
  devise_for :users, :path_prefix => 'my'

  resources :roles
  resources :users
  resources :notes do
    collection do
      get :all_notes
      get :get_user_notes
    end
  end
  resources :application do
    collection do
      post :index
    end
  end

  root to: 'notes#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
# frozen_string_literal: true
class User < ApplicationRecord
  ROLES = %i(admin head user banned).freeze

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :trackable,
         :validatable
  has_and_belongs_to_many :roles
  has_many :notes
  validates_presence_of :last_name
  validates :first_name, presence: true, length: { in: 1..255 }
  validates :last_name, length: { in: 1..255 }
  validates :head, default: false
  #

  def has_role?(role)
    roles.find_by_name(role) ? true : false
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  #load_and_authorize_resource

  def index
    @users =  current_user.admin? ? User.all : User.find([current_user.id])
  end

  def show
    @joined_on = @user.created_at.to_formatted_s(:short)
    if @user.current_sign_in_at
      @last_login = @user.current_sign_in_at.to_formatted_s(:short)
    else
      @last_login = 'never'
    end
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    if user_params[:password].blank?
      user_params.delete(:password)
      user_params.delete(:password_confirmation)
    end

    successfully_updated = if needs_password?(@user, user_params)
                             @user.update(user_params)
                           else
                             @user.update_without_password(user_params)
                           end

    respond_to do |format|
      if successfully_updated
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy!
    respond_to do |format|
      format.xml  { head :ok }
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  def needs_password?(_user, params)
    params[:password].present?
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :first_name, :last_name, :role_id, :telegram_id, :head, :admin)
  end
  ROLES = %i(admin).freeze
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.haml
=form_for(@user) do |f|
  -if @user.errors.any?
    %div{id: "error_explanation"}
      -@user.errors.full_messages.each do |message|
        =flash[:alert]=message

  %div.field
    =f.label :first_name, {class: "label label-default"}
    =f.text_field :first_name, {class: 'form-control input-sm'}

  %div.field
    =f.label :last_name, {class: "label label-default"}
    =f.text_field :last_name, {class: 'form-control input-sm'}

  %div.field
    =f.label :email, {class: "label label-default"}
    =f.text_field :email, {class: 'form-control input-sm'}

  %div.field
    =f.label :telegram_id, {class: "label label-default"}
    =f.text_field :telegram_id, {class: 'form-control input-sm'}

  %div.field
    =f.label :password, {class: "label label-default"}
    =f.text_field :password, {class: 'form-control input-sm'}

  %div
    %left
      -if @user.admin?
        =f.label :admin, {class: "label label-default"}
        =f.check_box :admin, {class: 'checkbox input-lg'}
    %right
      -if @user.admin? || @user.head?
        =f.label :head, {class: "label label-default"}
        =f.check_box :head, {class: 'checkbox input-lg'}

  %div.actions
    =f.submit 'Submit', class: 'btn btn-success'

app/views/users/edit.html.haml
%h1
  Editing User
%div.col-sm-8
  =render 'form', user: @user
  %div{class: 'btn-group btn-group'}
    =link_to 'Show', @user, {class: 'btn btn-default'}
    =link_to 'Back', users_path, {class: 'btn btn-default'}

app/views/users/index.html.haml
%h1 Users
.table-responsive
  %table.table
    %thead
      %tr
        %th Name
        %th Lastname
        %th Email
        %th Role
        %th{:colspan => "3"}
    %tbody
      - @users.each do |user|
        %tr
          %td= link_to "#{user.first_name}", notes_path
          %td= user.last_name
          %td= user.email
          - if user.admin?
            %td Admin
          - elsif user.head?
            %td Head
          - else
            %td User
          %td= link_to 'Show', user
          %td
            = link_to 'Edit', edit_user_path(user)
          %td
            - if can? :destroy, user
              = link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }
%br
- if can? :create, User
  = link_to 'New User', new_user_path, class: 'btn btn-default'

app/views/users/new.html.haml
%h1
  New User

%div{class: "col-sm-8"}
  = render 'form', user: @user
  =link_to 'Back', users_path, {class: 'btn btn-default'}

app/views/users/show.html.haml
%h1 User info
.col-sm-8
  %table.table.table-default
    %tr
      %td Firstname:
      %td= @user.first_name
    %tr
      %td Lastname:
      %td= @user.last_name
    %tr
      %td Email:
      %td= @user.email
    %tr
      %td Joined on:
      %td= @joined_on
    %tr
      %td Last login:
      %td= @last_login
    %tr
      %td No. times logged in:
      %td= @user.sign_in_count
  .btn.btn-group
    - if can? :update, @project
      = link_to 'Edit', edit_user_path(@user), class: 'btn btn-default'
    = link_to 'Back', users_path, class: 'btn btn-default'
    = link_to 'Add note', new_note_path(@user.id), class: 'btn btn-default'