config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  telegram_webhooks TelegramWebhooksController
  devise_for :users, :path_prefix => 'my'

  resources :roles
  resources :users
  resources :notes do
    collection do
      get :all_notes
      get :get_user_notes
    end
  end
  resources :application do
    collection do
      post :index
    end
  end

  root to: 'notes#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/role.rb
# frozen_string_literal: true
class Role < ApplicationRecord
  has_and_belongs_to_many :users

  validates :name, presence: true, length: { in: 1..255 }
  validates :description, length: { maximum: 1023 }
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_role, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  def index
    @roles = Role.all
  end

  def show
    if @role.users.length.zero?
      @assosciated_users = 'None'
    else
      @assosciated_users = @role.users.limit(10).map(&:name).join(', ')
    end
  end

  def new
    @role = Role.new
  end

  def edit
  end

  def create
    @role = Role.new(role_params)

    respond_to do |format|
      if @role.save
        format.html { redirect_to @role, notice: 'Role was successfully created.' }
        format.json { render :show, status: :created, location: @role }
      else
        format.html { render :new }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @role.update(role_params)
        format.html { redirect_to @role, notice: 'Role was successfully updated.' }
        format.json { render :show, status: :ok, location: @role }
      else
        format.html { render :edit }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @role.destroy
    respond_to do |format|
      format.html { redirect_to roles_url, notice: 'Role was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_role
    @role = Role.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def role_params
    params.require(:role).permit(:name, :description)
  end
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/roles/_form.html.haml
=form_for(@role) do |f|
  -if @role.errors.any?
    %div{id: "error_explanation"}
      -@role.errors.full_messages.each do |message|
        =flash[:alert]=message

  %div.field
    =f.label :name, {class: "label label-default"}
    =f.text_field :name, {class: 'form-control input-sm'}

  %div.field
    =f.label :description, {class: "label label-default"}
    =f.text_area :description, {class: 'form-control input-sm'}

    %div.actions
      =f.submit 'Submit', class: 'btn btn-success'

app/views/roles/edit.html.haml
%h1
  Editing Role
%div.col-sm-8
  =render 'form', role: @role
  %div{class: 'btn-group btn-group'}
    =link_to 'Show', @role, {class: 'btn btn-default'}
    =link_to 'Back', roles_path, {class: 'btn btn-default'}

app/views/roles/index.html.haml
%h1 Roles
.table-responsive
  %table.table
    %thead
      %tr
        %th Name
        %th Description
        %th{:colspan => "3"}
    %tbody
      - @roles.each do |role|
        %tr
          %td= role.name
          %td= role.description
          %td= link_to 'Show', role
          %td
            - if can? :update, role
              = link_to 'Edit', edit_role_path(role)
          %td
            - if can? :destroy, role
              = link_to 'Destroy', role, method: :delete, data: { confirm: 'Are you sure?' }
%br
- if can? :create, Role
  = link_to 'New Role', new_role_path, class: 'btn btn-default'

app/views/roles/new.html.haml
%h1
  New Role

%div{class: "col-sm-8"}
  = render 'form', role: @role
  =link_to 'Back', roles_path, {class: 'btn btn-default'}

app/views/roles/show.html.haml
%h1 Role info
.col-sm-8
  %table.table.table-default
    %tr
      %td Name:
      %td= @role.name
    %tr
      %td Description:
      %td= @role.description
    %tr
      %td Assosciated users:
      %td= @assosciated_users
  .btn.btn-group
    - if can? :update, @project
      = link_to 'Edit', edit_role_path(@role), class: 'btn btn-default'
    = link_to 'Back', roles_path, class: 'btn btn-default'