config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  telegram_webhooks TelegramWebhooksController
  devise_for :users, :path_prefix => 'my'

  resources :roles
  resources :users
  resources :notes do
    collection do
      get :all_notes
      get :get_user_notes
    end
  end
  resources :application do
    collection do
      post :index
    end
  end

  root to: 'notes#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.haml
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title BusinessCalendar
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

    %meta{name: "viewport", content: "width=device-width, initial-scale=1"}
    -#%link{rel: "stylesheet", href: "https://www.w3schools.com/w3css/4/w3.css"}
    -#%link{rel: 'stylesheet', href: 'https://fonts.googleapis.com/css?family=Roboto'}
    -#%link{rel: "stylesheet", href: "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"}
    %link{rel: "stylesheet", href: "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"}
    %script {src: "https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"}
    %script {src: "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"}

  %body
    %nav.navbar.navbar-inverse
      .container-fluid
        .navbar-header
          %button.navbar-toggle{type: "button", "data-toggle": "collapse", "data-target": "#myNavbar"}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.navbar-brand{href: notes_path} Your Calendar
        #myNavbar.collapse.navbar-collapse
          %ul.nav.navbar-nav
            -if current_user.admin? || current_user.head?
              %li.active
                \#{link_to "All Notes", all_notes_notes_path}
            %li.active
              \#{link_to "Users", users_path}
          .nav.navbar-nav.navbar-right
            %span.glyphicon.glyphicon-log-in
              - if user_signed_in?
                = link_to "#{current_user.email}"
                \#{link_to "Sign out", destroy_user_session_path, :method => :delete}
              - else
                = link_to "Sign up", new_user_registration_path
                or #{link_to "sign in", new_user_session_path}
    - flash.each do |type, message|
      .col-s1-8
        .container
          %div{:class => "alert #{bootstrap_class_for(type)} fade in"}
            = message

    .container-fluid.text-center
      .row.content
        .col-sm-2
          .container-fluid

        .col-sm-8.text-left
          = yield

  %container-fluid.footer.text-center
    %p Hrodna, 2016-2017

app/views/layouts/devise.html.haml
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title BusinessCalendar
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

    %meta{name: "viewport", content: "width=device-width, initial-scale=1"}
    %link{rel: "stylesheet", href: "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"}
    %script {src: "https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"}
    %script {src: "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"}

  %body
    %nav.navbar.navbar-inverse
      .container-fluid
        .navbar-header
          %button.navbar-toggle{type: "button", "data-toggle": "collapse", "data-target": "#myNavbar"}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.navbar-brand{href: notes_path} Your Calendar
        #myNavbar.collapse.navbar-collapse
          .nav.navbar-nav.navbar-right
            %span.glyphicon.glyphicon-log-in
              - if user_signed_in?
                = link_to "#{current_user.email}"
                \#{link_to "Sign out", destroy_user_session_path, :method => :delete}
              - else
                = link_to "Sign up", new_user_registration_path
                or #{link_to "sign in", new_user_session_path}
    - flash.each do |type, message|
      .col-s1-8
        .container
          %div{:class => "alert #{bootstrap_class_for(type)} fade in"}
            = message

    .container-fluid.text-center
      .row.content
        .col-sm-2

        .col-sm-8.text-left
          = yield

  %container-fluid.footer_singlepage.text-center
    %p Hrodna, 2016-2017

app/views/layouts/notes.html.haml
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title BusinessCalendar
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

    %meta{name: "viewport", content: "width=device-width, initial-scale=1"}
    %link{rel: "stylesheet", href: "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"}
    %script {src: "https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"}
    %script {src: "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"}

  %body
    %nav.navbar.navbar-inverse
      .container-fluid
        .navbar-header
          %button.navbar-toggle{type: "button", "data-toggle": "collapse", "data-target": "#myNavbar"}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.navbar-brand{href: notes_path} Your Calendar
        #myNavbar.collapse.navbar-collapse
          %ul.nav.navbar-nav
            -if current_user.admin? || current_user.head?
              %li.active
                \#{link_to "All Notes", all_notes_notes_path}
            %li.active
              \#{link_to "Users", users_path}
          .nav.navbar-nav.navbar-right
            %span.glyphicon.glyphicon-log-in
              - if user_signed_in?
                = link_to "#{current_user.email}"
                \#{link_to "Sign out", destroy_user_session_path, :method => :delete}
              - else
                = link_to "Sign up", new_user_registration_path
                or #{link_to "sign in", new_user_session_path}
    - flash.each do |type, message|
      .col-s1-8
        .container
          %div{:class => "alert #{bootstrap_class_for(type)} fade in"}
            = message

    .container-fluid.text-center
      .row.content
        .col-sm-2

        .col-sm-8.text-left
          = yield

  %container-fluid.footer.text-center
    %p Hrodna, 2016-2017